#!/usr/bin/env bash
# A script to transfer a file from the client to a remote server
# there will be for parameters
# 1 the path to the file to be transferred
# 2 the ip of the server we want to transfer to
# 3 the username scp connects with
# 4 the path to the SSH private key that scp uses
# we have to make sure stricthostkeychecking is set to no

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
