#!/usr/bin/env bash
# this is a bash script that configures a new ubuntu machine
# with the following requirements
# to install nginx on the server
# Nginx should be listening on port 80
# and when we type curl localhost we should get
# Hello World!

# updating and installing Nginx

sudo apt-get update -y
sudo apt-get install nginx -y

# making sure nginx listens on port 80

sudo ufw allow 'Nginx HTTP'

# give the user permissionsa and ownership to edit the websites

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 744 /var/www


echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
