#!/usr/bin/env bash
# this is a bash script that configures a new ubuntu machine
# with the following requirements
# to install nginx on the server
# Nginx should be listening on port 80
# and when we type curl localhost we should get
# Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/firstPage.html > /dev/null
service nginx start
