#!/usr/bin/env bash
# this script sets up a new ubuntu machine, with
# Nginix installed where which will be listening 
# on port 80. with the /redirect_me is redirecting
# to another page

sudo apt-get -y update
sudo apt-get -y install nginx
# making sure nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'
# give the user permissionsa and ownership to edit the websites
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 744 /var/www
echo "Hello World!" > /var/www/html/index.html
# setting up the /redirect_me to a youtube video using sed command
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
