#!/usr/bin/env bash
# this script sets up a new ubuntu machine, with
# Nginix installed where which will be listening 
# on port 80. with the /redirect_me is redirecting
# to another page

sudo apt-get update -y
sudo apt-get install nginx -y
# making sure nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'
# give the user permissionsa and ownership to edit the websites
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 744 /var/www
echo "Hello World!" > /var/www/html/index.html
# setting up the /redirect_me to a youtube video using sed command with a return of 301

New_config = "\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

# let's back up the original default page
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "53i $New_config" /etc/nginx/sites-available/default
sudo service nginx restart
